# Generated by Django 5.0.6 on 2024-09-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Namemonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
