# Generated by Django 5.0.6 on 2024-09-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bors", "0002_namemonth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricechange",
            name="month",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bors.namemonth"
            ),
        ),
    ]
