# Generated by Django 5.0.6 on 2024-09-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bors", "0003_alter_pricechange_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="profit",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
