# Generated by Django 5.0.6 on 2024-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bors", "0005_alter_investment_initial_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricechange",
            name="price",
            field=models.IntegerField(),
        ),
    ]
